### ISSUE TITLE
request to split build and push steps

### ISSUE THREAD

**Issue by isa220** [CircleCI-Public/azure-acr-orb#14]
### Orb version
v0.2.0

### What happened
there is combined build_and_push job, so push goes immediately after build

### Expected behavior
steps "build" and "push" separated, so i can run some extra tests before i push image to registry.

**Comment by EricRibeiro** [comment]
Hi, @isa220 👋 

Although your suggestion makes sense, this is not something that we will implement now. It will be considered in major change down the road.

In the meantime, you can accomplish this by putting together your own job with the `azure-cli`, `azure-acr` and `docker` orbs:

```
...

steps:
  - when:
      condition: <<parameters.checkout>>
      steps:
        - checkout

  - azure-cli/install

  - azure-cli/login-with-user-or-service-principal:
      azure-username: <<parameters.azure-username>>
      azure-password: <<parameters.azure-password>>
      azure-sp: <<parameters.azure-sp>>
      azure-sp-password: <<parameters.azure-sp-password>>
      azure-sp-tenant: <<parameters.azure-sp-tenant>>
      alternate-tenant: <<parameters.alternate-tenant>>
      azure-tenant: <<parameters.azure-tenant>>

  - when:
      condition: <<parameters.attach-workspace>>
      steps:
        - attach_workspace:
            at: <<parameters.workspace-root>>

  - azure-acr/acr-login:
      registry-name: <<parameters.registry-name>>
      configure-docker-credentials-store: <<parameters.configure-docker-credentials-store>>

  - docker/build:
      step-name: Build Docker image for ACR
      dockerfile: <<parameters.dockerfile>>
      path: <<parameters.path>>
      image: <<parameters.repo>>
      tag: <<parameters.tag>>
      extra_build_args: <<parameters.extra-build-args>>
      lint-dockerfile: <<parameters.lint-dockerfile>>
      treat-warnings-as-errors: <<parameters.treat-warnings-as-errors>>
      registry: <<parameters.login-server-name>>

  - < your tests here >

  - docker/push:
      step-name: Push Docker image to ACR
      registry: <<parameters.login-server-name>>
      image: <<parameters.repo>>
      tag: <<parameters.tag>>
```

The above was extracted and adapted from the [build-and-push-image.yml](https://github.com/CircleCI-Public/azure-acr-orb/blob/master/src/commands/build-and-push-image.yml) command and should give a direction on how to proceed.

Feel free to open another issue or post it here should you have further questions.
