### ISSUE TITLE
PublicAccessNotPermitted running `curl -L https://aka.ms/acr/installaad/bash | /bin/bash script`

### ISSUE THREAD

**Issue by ds-combine-ai** [CircleCI-Public/azure-acr-orb#28]
### Orb version
0.2.2

### What happened
When running with this orb, for the "Configure Azure ACR Helper" step:

```
#!/bin/bash -eo pipefail
# Run ACR Docker Credential Helper installation script
# https://github.com/Azure/acr-docker-credential-helper#installation
curl -L https://aka.ms/acr/installaad/bash | /bin/bash
```

received an error:

```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   248  100   248    0     0    806      0 --:--:-- --:--:-- --:--:--   806
/bin/bash: line 1: syntax error near unexpected token `<'
/bin/bash: line 1: `<?xml version="1.0" encoding="utf-8"?><Error><Code>PublicAccessNotPermitted</Code><Message>Public access is not permitted on this storage account.'

Exited with code exit status 2
```

### Expected behavior

It normally connects and runs the script

**Comment by AlaaNabil26** [comment]
I have same problem any updates ?

**Comment by ds-combine-ai** [comment]
Thanks lcssanches for the workaround - will try it.  I've been building things locally in the meantime.  It would still be nice to get this fixed in the orb as well 🙇

**Comment by alan-cushla** [comment]
@brentmmarks sorry for the random ping but you're the last person to commit to this repo. Can you help with this?

**Comment by AlaaNabil26** [comment]
we are blocked for 4 days why no one help with this ??

**Comment by alan-cushla** [comment]
It looks like the orb is using the [acr docker credential helper](https://github.com/Azure/acr-docker-credential-helper) which has a deprecation notice. I suspect the file it's trying to download has been removed or otherwise changed.

**Comment by david-montano-circleci** [comment]
Hello everyone. I will be adding a test to replicate this and will push for a solution this week.

**Comment by ds-combine-ai** [comment]
Awesome news, thanks for the update 👍

**Comment by no-man-is-an-island** [comment]
Any update on this one?

**Comment by david-montano-circleci** [comment]
Small update: we have replicated the issue and we are looking which alternative solutions we have to solve it. Still working on this with high priority.

**Comment by david-montano-circleci** [comment]
A quick solution is to skip the `configure-docker-credentials-store` from the `acr-login` command by setting the `configure-docker-credentials-store` parameter as `false`. Here is an example:

```
workflows:
  test-deploy:
    jobs:
      - azure-acr/build-and-push-image:
          name: build-and-push
          context: ******
          registry-name: *******
          login-server-name: *******
          azure-sp-tenant: *****
          azure-sp: *****
          azure-sp-password: *******
          dockerfile: test.Dockerfile
          path: test
          repo: ********
          configure-docker-credentials-store: false
          tag: $CIRCLE_BUILD_NUM
          filters: *filters
```

This will work only if the service provider is correctly setup in Azure.

<img width="913" alt="Image" src="https://github.com/user-attachments/assets/e5e4664e-db7b-43c8-b6f8-870c242b202b" />

Fixing the access to https://aka.ms/acr/installaad/bash seems not an option so we will probably remove that logic from the orb.

Please let me know if this solution (setting `configure-docker-credentials-store: false`) works while we try to decide if we remove the mentioned logic (thus generating a new minor version of this orb) or if there is something else we can do.

**Comment by AlaaNabil26** [comment]
yes "configure-docker-credentials-store: false " worked for me 
Thank You. @david-montano-circleci

**Comment by ds-combine-ai** [comment]
Great, thanks @david-montano-circleci, I confirm this also fixed for me.  I like this style more actually, as it's more obvious where it's picking up the ENV vars from.  You could just remove the step that runs https://aka.ms/acr/installaad/bash, and then update docs to ensure everyone uses explicit ENV vars on the job definition?

One little gotcha, when defining the ENV vars to use, I had to use this format:

```
- azure-acr/build-and-push-image:
    ...(skipping other config)...
    configure-docker-credentials-store: false
    azure-sp-tenant: AZURE_SP_TENANT
    azure-sp: AZURE_SP
    azure-sp-password: AZURE_SP_PASSWORD
```

If you try to use `$` format for these ENV vars, you'll get a validation error:

```
Error calling command: 'azure-acr/build-and-push-image'
Type error for argument azure-sp-password: expected type: env_var_name, actual value: "$AZURE_SP_PASSWORD" (type string)
Type error for argument azure-sp: expected type: env_var_name, actual value: "$AZURE_SP" (type string)
```
